### ISSUE TITLE
Stacktrace java.lang.NoSuchFieldError: ccLang

### ISSUE THREAD

**Issue by Nubebuster** [dniym/IllegalStack#52] opened 2020-06-09 02:38 UTC
[04:36:29 ERROR]: Could not pass event InventoryOpenEvent to IllegalStack v2.1.2d
java.lang.NoSuchFieldError: ccLang
        at enums.Protections.isThirdPartyInventory(Protections.java:859) ~[?:?]
        at main.fListener.onShulkerCheck(fListener.java:724) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor64.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-341]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-341]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-341]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-341]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1214) ~[patched_1.15.2.jar:git-Paper-341]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1200) ~[patched_1.15.2.jar:git-Paper-341]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftHumanEntity.openCustomInventory(CraftHumanEntity.java:359) ~[patched_1.15.2.jar:git-Paper-341]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:344) ~[patched_1.15.2.jar:git-Paper-341]
        at me.sat7.dynamicshop.DynaShopAPI.openItemTradeGui(DynaShopAPI.java:46) ~[?:?]
        at me.sat7.dynamicshop.transactions.Buy.buyItemCash(Buy.java:123) ~[?:?]
        at me.sat7.dynamicshop.events.OnClick.OnInvenClick(OnClick.java:975) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor109.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-341]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-341]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-341]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-341]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2375) ~[patched_1.15.2.jar:git-Paper-341]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-341]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-341]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-341]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-341]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-341]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-341]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-341]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1097) ~[patched_1.15.2.jar:git-Paper-341]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090) ~[patched_1.15.2.jar:git-Paper-341]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-341]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1051) ~[patched_1.15.2.jar:git-Paper-341]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:966) ~[patched_1.15.2.jar:git-Paper-341]
        at java.lang.Thread.run(Thread.java:834) [?:?]

413 paperspigot
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)

**Comment by dniym** [comment] 2020-06-09 02:43
hmmm did you recently upgrade the DyamicShop plugin?  if so this may be the cause, it appears IllegalStack can't find something it is looking for in the DynamicShop plugin's jar file.

On another note you are running one version behind on IllegalStack.

**Comment by Nubebuster** [comment] 2020-06-10 01:04
I'll update it and see if the error is fixed. I don't recall updating DynamicShop.
I'll get back in a few days. The server is having some other issues and I don't really know how to reproduce the bug since it's the playerbase unknowingly doing it...

**Comment by dniym** [comment] 2020-06-10 01:29
Well based on the error message it is happening when an inventory is opened, and the plugin is trying to check if it is an inventory that belongs to dynamicshop.   It only does that if it detects dynamicshop installed on the server when IllegalStack starts.  


Possible causes:
1) dynamicshop was updated and their code has changed, and the method that IllegalStack is trying to use no longer exists. 

2) the plugin is there When IllegalStack was loaded but was then later unloaded so IS is trying to use the plugin and failing. 

3) similar to scenario 2 the plugin has broken for some reason and didn’t enable and isn’t functioning so IS can’t find the method it needs.

**Comment by jmanpenilla** [comment] 2020-06-11 07:48
It's to do with an issue in DynamicShop. I haven't been able to track down the bug yet, but I have an issue open on the repo [here](https://github.com/7sat/SSDynamicShop/issues/13)

**Comment by dniym** [comment] 2020-06-11 12:24
They changed some things around in the plugin is all, I’ve got a dev version you can have right now if you want to send me a messsge on discord, otherwise it will be fixed as soon as the next version of IllegalStack is ready for release.

**Closed** 2023-06-14 21:46 UTC
